[[Bullet_Physics_SDK]]
arch = "aarch64"
git-tree-sha1 = "fc2275d119de1fd59d8bd112f021486b3504d3aa"
os = "macos"

    [[Bullet_Physics_SDK.download]]
    sha256 = "b05a99f59a7c02e6b851535e25df43de87b63c0e8c03b14dc2e87ce037879c2b"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.aarch64-apple-darwin.tar.gz"
[[Bullet_Physics_SDK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ec37bc12172f8c9edb0dbc41810f637c609f4e58"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "267ecda51ba2b1a7af3ad25ce034342d8ca034a15572d43a92dbaa816aec5bcb"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dab3c4375cc787b98ad4efcc4b1282ca202a2756"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "597aa74710256e093d184c84a70429e911aca452cae6f2f7ee99167d3ebfef89"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b40270fdf3a1528cdcd63e92337fbc9e5b91635e"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "27bc8b81f20a1a2843439f3b0dd9db036acaf1fff981e33686a4b5a49111d907"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.aarch64-linux-musl-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7b8769f15a0c4ced6b33474165ea9f779f636a78"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "700f7473fbb3534bd8b62d57cbc1f0d0244cb44c755dbece18f383882ae21548"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.aarch64-linux-musl-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6ca8e48eb624b0d50ed1a7c5fa5e7bee230291c"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "3c0113ad9f0126e4d4eabbbd0dbca5547bed54964a16a8b2fdf5f1ba32524e59"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c05b72848298d8ab02b1b86c7e521f621ebcc87"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "f1ac0d53fe2c1c25eafe6e9f87eb1bda9c3d6172e4faec20cecc092efdb1883e"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e03f31d62a2a2fffd02218c84029e3424ceb38a9"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "0d38edfb2bf2053643f8483e3c2e85eda8bc9bb85a61a1b3cd6f0d9b5b8d7feb"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8ed98b38fb0b2feacafd866e097ad0f325144a8c"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "b2cc71e11eae4665abb2bcbfc1d5d8366aa8ad519d3b6fdc14caef9d78846101"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b100d796ecad731004b5412f10d3fbc9679a99b"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "31943b8b6c99996a5a39254156dec46607814b5da79434eb7494b5225bef0e56"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "262c4546cbf113c295196e3b4910a735ce75ecd0"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "f2fada86e1385621a951672d570aa24021a43aff92e50815b1b74b9f20347dc1"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d765318aba9987e5095c81bb64f199b99fb336af"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "f4f4cc34a223554c66ff983bbda1782dc28c1ba7b868ee6786666a62747759c6"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5e2975a5e0591c4868b376ffd28f653166d43819"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "7ff464da4cb1c8ca556a5ec6f880c0f4c22706f06c662347ba0e255d6e63dbcd"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f45a41c5ca5164b3a954a7c2aeea2afc44bdb48c"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "5bb0784fb5f5f2705f49e2e1561b8ab0f123027ec795a34ab4b0754866bf1524"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.i686-linux-gnu-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eb23e75a160043685dbc2ae5639db81e3a6a6ba1"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "d6097922d56c03bf8c21987848dec944c2cf83c85c298145b8189da4f5b91f65"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.i686-linux-gnu-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "90e964c54ce99906eb8bb5316ac044dc7111d05a"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "e7fae5eec370b1594ce376997aebe8f8c8a783eaec58a31e15b6eaf9bfebefed"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.i686-linux-musl-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "484196d3980bb984fab81b8e275d9abf6ffc6e2d"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "3681faca1dce0780fd819082e95ae3682945edbb2e9c4153d4a83c07d30a37bb"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.i686-linux-musl-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "84688f1abf5cc0e82dde3bc3c2b06f9085e1071a"
os = "windows"

    [[Bullet_Physics_SDK.download]]
    sha256 = "071890761399d0548d89929bde5675885083c85d1c532357453bd67a7adee3ed"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.i686-w64-mingw32-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60269dd7ee12404cf7821f7e7cd69f6029ce0a93"
os = "windows"

    [[Bullet_Physics_SDK.download]]
    sha256 = "3c0bdb1431f4e676553f8972ebb02ee60a11acbbf3992121495f5edb0aceb780"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.i686-w64-mingw32-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2458ee5391a83c8593ea007f4bdc15e4d1bc4de5"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "ae3d9acd53159d999f0e99ac69378f7577599f757f95898617e959b2c175ed14"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "96dde7d5058b52a5162800642c3f832bcf165f91"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "6dea92b747ba0e91811e6fd9addcc1e18e0c4e48ff83a88a29a73815f14c5286"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
git-tree-sha1 = "ac7da2ff29100927507429b6286afec443db313b"
os = "macos"

    [[Bullet_Physics_SDK.download]]
    sha256 = "437256f8b0657254da0bce42c981678d4203a044ea9f55d2ec6a4ad8583092ff"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-apple-darwin.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b61dc7873ca3afcabef5f07c4b5a3ab01e98686e"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "eb5eef5fc1033e9a1493ae41c58766f8a2500284e99e09d613f5c24066d7b13f"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "25a4626d6f0567dc378db73a94ba9804d0693eba"
libc = "glibc"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "1fb77f531d16dcd94604f42f2f0a3b2842fe96942e3a4a66db9afedeb0247f22"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6f7a8b4bb4ced462a76e0e43b573cc8c4c128660"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "2079810ecc0d8755dc3acb79a67693243d5a6d8c5a0cec9d3ce4b5afe0d29bc8"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-linux-musl-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "00ba5d96071ee77183e122a4a5caf8ee532624ba"
libc = "musl"
os = "linux"

    [[Bullet_Physics_SDK.download]]
    sha256 = "217a437bd5cad889c1fd19071f754b7223d545ec501f141fdd2fa85098064074"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-linux-musl-cxx11.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
git-tree-sha1 = "3081d2f675dec67ebd0da8577876782107c675df"
os = "freebsd"

    [[Bullet_Physics_SDK.download]]
    sha256 = "268920968f856852fe6474c1c6266023210defccd5d9729367d97e252d2de700"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-unknown-freebsd.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ecb132a7260cb545cdcecca9270073da570af0e5"
os = "windows"

    [[Bullet_Physics_SDK.download]]
    sha256 = "178d2e8f2cc556a3d15c4bf8a84924a9f34685523423ad73c142c550de491b31"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Bullet_Physics_SDK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c25113f291d0729c1e759f1ac5a60ca960d57dc4"
os = "windows"

    [[Bullet_Physics_SDK.download]]
    sha256 = "d4bd44d34a552aea156f226943b90393018cf88a46f70236a6c0872f2c41742b"
    url = "https://github.com/JuliaBinaryWrappers/Bullet_Physics_SDK_jll.jl/releases/download/Bullet_Physics_SDK-v3.22.0+1/Bullet_Physics_SDK.v3.22.0.x86_64-w64-mingw32-cxx11.tar.gz"
